package com.example.culturequest.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single quiz question in the app.
 *
 * This data class is used as a Room entity to store questions in the "quiz_questions" table.
 *
 * @property id The unique identifier for the question, automatically generated by the database.
 * @property questionText The text of the quiz question.
 * @property correctAnswer The correct answer for the question.
 */
@Entity(tableName = "quiz_questions")
data class QuizQuestion(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val questionText: String,
    var correctAnswer: String,
)
