package com.example.culturequest.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a user profile in the app.
 *
 * This data class is used as a Room entity to store user profiles in the "user_profile" table.
 *
 * @property id The unique identifier for the user profile, automatically generated by the database.
 * @property uid The Firebase UID of the user, or a local guest ID.
 * @property username The name of the user.
 * @property score The user's current score.
 * @property bestScore The user's all-time high score.
 * @property gamesPlayed The total number of games the user has played.
 */
@Entity(tableName = "user_profile")
data class UserProfile(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val uid: String,
    val username: String,
    val score: Int,
    val bestScore: Int = 0,
    val gamesPlayed: Int = 0,
)
