package com.example.culturequest.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF386A1F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB7F396)
val md_theme_light_onPrimaryContainer = Color(0xFF052100)
val md_theme_light_secondary = Color(0xFF55624C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD9E7CB)
val md_theme_light_onSecondaryContainer = Color(0xFF131F0D)
val md_theme_light_tertiary = Color(0xFF386668)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBBEBED)
val md_theme_light_onTertiaryContainer = Color(0xFF002021)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFFDFDF5)
val md_theme_light_onBackground = Color(0xFF1A1C18)
val md_theme_light_surface = Color(0xFFFDFDF5)
val md_theme_light_onSurface = Color(0xFF1A1C18)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFF9CDF7D)
val md_theme_dark_onPrimary = Color(0xFF163900)
val md_theme_dark_primaryContainer = Color(0xFF245106)
val md_theme_dark_onPrimaryContainer = Color(0xFFB7F396)
val md_theme_dark_secondary = Color(0xFFBDCBAF)
val md_theme_dark_onSecondary = Color(0xFF283420)
val md_theme_dark_secondaryContainer = Color(0xFF3E4A35)
val md_theme_dark_onSecondaryContainer = Color(0xFFD9E7CB)
val md_theme_dark_tertiary = Color(0xFF9FCFCC)
val md_theme_dark_onTertiary = Color(0xFF003739)
val md_theme_dark_tertiaryContainer = Color(0xFF1E4E50)
val md_theme_dark_onTertiaryContainer = Color(0xFFBBEBED)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_background = Color(0xFF1A1C18)
val md_theme_dark_onBackground = Color(0xFFE3E3DC)
val md_theme_dark_surface = Color(0xFF1A1C18)
val md_theme_dark_onSurface = Color(0xFFE3E3DC)
